version: '3.8'

services:
  backend_api:
    build: 
      context: ../../../backend
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - TEST_GOOGLE_IDENTITY_CERT=/app/config/google_identity.crt
    volumes:
      - ../../../backend/coverage:/backend/coverage
    secrets:
      - source: google-identity-cert
        target: /app/config/google_identity.crt
  mail:
    hostname: mail.dev.wsl
    image: maildev/maildev
    networks:
      - backend_spawner
    ports:
      - "1080:1080" # web/api interface
  db:
    networks:
      - backend_spawner
secrets:
  google-identity-cert:
    file: ../shared/google_identity.crt