version: '3.8'

services:
  backend_api:
    build: 
      context: ../../../backend
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    volumes:
      - ../../../backend/coverage:/backend/coverage
  mail:
    hostname: mail.dev.wsl
    image: maildev/maildev
    networks:
      - backend_spawner
    ports:
      - "1080:1080" # web/api interface