#!/bin/sh

docker build --no-cache \
    -t frontend_builder \
    -f ./frontend/Dockerfile ../../../frontend && \
docker run --rm --name frontend_builder -t \
    --env-file ./config/frontend.env \
    -v frontend_static:/build/dist frontend_builder && \
docker compose \
    -f ./docker-compose.yml \
    -f ./docker-compose.test.yml \
    up -d --build