#!/bin/sh

set -eu

KB_GAME_TEST_DIR="$PWD"

npm i -g c8

mkdir -p -- ./spawner/coverage ./backend/coverage

mkdir -p ../deploy/docker-compose/shared
echo "$TEST_GOOGLE_IDENTITY_CERT" > '../deploy/docker-compose/shared/google_identity.crt'
echo "$TEST_GOOGLE_IDENTITY_KEY" > '../deploy/docker-compose/shared/google_identity.key'
sed -i "s/\[clientId\]/$TEST_GOOGLE_CLIENT_ID/" ../deploy/docker-compose/backend/config/backend.json

# Setup backend
echo "$SSL_CA" > '../deploy/docker-compose/backend/config/root.crt'
echo "$SSL_CERTS" > '../deploy/docker-compose/backend/config/server.cert'

# Setup spawner
echo "$SSL_CA" > '../deploy/docker-compose/spawner/config/root.crt'
echo "$SSL_CERTS" > '../deploy/docker-compose/spawner/config/server.cert'

cp ./spawner/settings.json ../deploy/docker-compose/spawner/config/settings.json && \
    sed -i -e "s|\[CA_PATH\]|${PWD}/../deploy/docker-compose/spawner/config|g" \
    ../deploy/docker-compose/spawner/config/settings.json

# Setup docker environment
docker network create backend_spawner

# Start backend
cd ../deploy/docker-compose/backend && \
    chmod +x ./run_test && \
    ./run_test

# Start spawner
cd "$KB_GAME_TEST_DIR" && \
    cd ../deploy/docker-compose/spawner && \
    chmod +x ./run_test && \
    ./run_test

cd "$KB_GAME_TEST_DIR" && \
docker build --no-cache \
    --build-arg SSL_CA="$SSL_CA" \
    -t tester . && \
docker run --rm --name tester \
    -e GOOGLE_IDENTITY_CERT='/google-identity/google_identity.crt' \
    -e GOOGLE_IDENTITY_KEY='/google-identity/google_identity.key' \
    -e GOOGLE_CLIENT_ID=$TEST_GOOGLE_CLIENT_ID \
    -v ${PWD}/../deploy/docker-compose/shared:/google-identity \
    --network backend_spawner -t \
    tester

docker stop $(docker ps -q -f "name=ga_")
docker stop spawner-spawner-1
docker stop backend-backend_api-1

sudo chown -R $(id -u):$(id -g) ../spawner/coverage && \
sudo chown -R $(id -u):$(id -g) ../backend/coverage
