version: '3.8'

services:
  spawner:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    volumes:
      - ..:/workspace/spawner:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../game_instance:/workspace/game_instance
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spawner.rule=Host(`spawner.dev.wsl`)"
      - "traefik.http.services.spawner.loadbalancer.server.port=80"
      - "traefik.http.routers.spawner.entrypoints=websecure"
      - "traefik.http.routers.spawner.tls=true"

    command: sleep infinity
    
    networks:
       - dev
  proxy_spawner:
    hostname: spawner.dev.wsl
    image: traefik:2.8.0
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ../../certs:/certs
        - ./traefik:/etc/traefik
    networks:
        - dev
    ports:
        - "443:443"
        - "8081:8080"
networks:
  dev:
    external: true   