import { ButtonLayout } from './button-layout';

export const layout: ButtonLayout[] = [
  { caption: ['~', '`'], code: 'Backquote' },
  { caption: ['!', '1'], code: 'Digit1' },
  { caption: ['@', '2'], code: 'Digit2' },
  { caption: ['#', '3'], code: 'Digit3' },
  { caption: ['$', '4'], code: 'Digit4' },
  { caption: ['%', '5'], code: 'Digit5' },
  { caption: ['^', '6'], code: 'Digit6' },
  { caption: ['&', '7'], code: 'Digit7' },
  { caption: ['*', '8'], code: 'Digit8' },
  { caption: ['(', '9'], code: 'Digit9' },
  { caption: [')', '0'], code: 'Digit0' },
  { caption: ['_', '-'], code: 'Minus' },
  { caption: ['+', '='], code: 'Equal' },

  { caption: 'Q', code: 'KeyQ' },
  { caption: 'W', code: 'KeyW' },
  { caption: 'E', code: 'KeyE' },
  { caption: 'R', code: 'KeyR' },
  { caption: 'T', code: 'KeyT' },
  { caption: 'Y', code: 'KeyY' },
  { caption: 'U', code: 'KeyU' },
  { caption: 'I', code: 'KeyI' },
  { caption: 'O', code: 'KeyO' },
  { caption: 'P', code: 'KeyP' },
  { caption: ['[', '{'], code: 'BracketLeft' },
  { caption: [']', '}'], code: 'BracketRight' },
  { caption: ['\\', '|'], code: 'Backslash' },

  { caption: 'A', code: 'KeyA' },
  { caption: 'S', code: 'KeyS' },
  { caption: 'D', code: 'KeyD' },
  { caption: 'F', code: 'KeyF' },
  { caption: 'G', code: 'KeyG' },
  { caption: 'H', code: 'KeyH' },
  { caption: 'J', code: 'KeyJ' },
  { caption: 'K', code: 'KeyK' },
  { caption: 'L', code: 'KeyL' },
  { caption: [';', ':'], code: 'Semicolon' },
  { caption: ['\'', '"'], code: 'Quote' },

  { caption: 'Z', code: 'KeyZ' },
  { caption: 'X', code: 'KeyX' },
  { caption: 'C', code: 'KeyC' },
  { caption: 'V', code: 'KeyV' },
  { caption: 'B', code: 'KeyB' },
  { caption: 'N', code: 'KeyN' },
  { caption: 'M', code: 'KeyM' },
  { caption: [',', '<'], code: 'Comma' },
  { caption: ['.', '>'], code: 'Period' },
  { caption: ['/', '?'], code: 'Slash' }];
