version: '3.8'

services:
  spawner:
    build: 
      context: ../../../spawner
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    volumes:
      - ../../../spawner/coverage:/spawner/coverage