name: integration-test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name Pre run
        run: tree . 
      - name: Run
        env:
          SSL_CA: ${{ secrets.SSL_CA }}
          SSL_CERTS: ${{ secrets.SSL_CERTS }}
        run: cd test && chmod +x ./run && ./run
      - name Print coverage
        run: tree . 
      - name: Upload backend codecov
        uses: codecov/codecov-action@v3
        with:
          flags: backend
          directory: ./backend/coverage
      - name: Upload spawner codecov
        uses: codecov/codecov-action@v3
        with:
          flags: spawner
          directory: ./spawner/coverage
